version: '3.8'

services:
  app:
    image: node:12.15
    cap_add:
      - SYS_ADMIN
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules/
    ports:
      - 8080:8080
      - 3000:3000
    tty: true
    command: "bash"
